<?php

$helper = $this->helper('Webkul\Marketplace\Helper\Data');
$partner = $block->getProfileDetail();
$shopUrl = $block->escapeHtml($partner['shop_url']);
$sellerbadges = $block->getSellerBadges();
ksort($sellerbadges);
$badgeDesc = [];
?>
<div class="wk_mp_design">
	<?php echo $block->getChildHtml("marketplace_seller_top_block")?>
	<div class="wk-mp-collection-container">
    <div class="block badge-block-account" id="badge-block">   
        <div class="block-title">
            <strong><span><h4><?php echo __("Seller Badge(s)") ?></h4></span></strong>
        </div>
        <fieldset class="fieldset info wk-mp-fieldset">
                <div class="field">
                    <?php if(count($sellerbadges) > 0){ ?>
                    <?php foreach($sellerbadges as $key => $val ) { 
                        $badgeDesc[$key]= ['desc' => $val['desc'],'name' => $val['title']];
                    ?>
                    <div style="margin:10px;display:inline-block">
                    <div class="tooltip">
                        <img src="<?php /* @escapeNotVerified */ echo $val['url'] ;?>" width="100" height="100">	
                            <span class="tooltiptext">
                                <?php 
                                $sellerDescLenght = strlen($val['desc']);
                                echo substr($val['desc'],0,100);
                                if ($sellerDescLenght>100) { ?>
                                    <a href="#!" class="badge" bid="<?php echo $key; ?>">Read More....</a>
                                <?php }
                                ?>
                            </span>
                    </div>
                    </div>
                    
                    <?php 		} 
                            }else{ ?>
                            <div class="wk_profile_alert">
                            <strong><?php /* @escapeNotVerified */ echo __('There is no badge assigned to seller.'); ?></strong>
                            </div>
                            
                            <?php }

                        ?>
                </div>
        </fieldset>
    </div>
	</div>
</div>
<div id="custom-model-popup">
    <dl>
    </dl>
</div> 
<script type="text/x-magento-init">
	{
	    "*": {
	        "sellerBadgeDescription": <?php echo json_encode($badgeDesc); ?>
	    }
	}
</script>