<?php
/**
 * @category   Webkul
 * @package    Webkul_MpSellerBadge
 * @author     Webkul Software Private Limited
 * @copyright  Copyright (c)  Webkul Software Private Limited (https://webkul.com)
 * @license    https://store.webkul.com/license.html
 */

$partner = $block->getProfileDetail();
$shopUrl = $escaper->escapeHtml($partner['shop_url']);
?>
<div class="wk-mp-seller-profile-box wk-mp-badges-order-count-container wk-mp-collection-header-bottom-txt">
    <a class="mp-badge" href="<?= $escaper->escapeUrl($block->getUrl(
        'mpsellerbadge/badge/index',
        ['shop' => $shopUrl]
    )); ?>#badge-block"><?= $escaper->escapeHtml(__('Badge(s)')); ?></a>
</div>
