<?php
$helper = $block->mpHelperObj();
$mpHelper = $block->mpsellerbadgeHelperObj();
$imageHelper = $block->imageHelperObj();
$bestSellersData = $block->getSellers();
$seller_arr = $bestSellersData['0'];
$sellerProfileArr = $bestSellersData['1'];
$sellerCountArr = $bestSellersData['2'];
$sellerBadgeArr = $bestSellersData['3'];
$widgetData = $block->getData();
$placeholderImageUrl = $imageHelper->getDefaultPlaceholderUrl('small_image');
?>
<link rel="stylesheet" mime-type="text/css" href="<?= $escaper->escapeUrl(
    $block->getViewFileUrl('Webkul_MpSellerBadge/css/sellerbadge.css')
); ?>">
<?php if ($helper->getSellerProfileDisplayFlag()) { ?>
    <div class="wk-mp-design wk-mp-landingpage wk-mp-landingpage-layout1" style="overflow:auto;">
        <div class="wk-marketplace-label" style="text-align:center;padding-bottom:1.2%;">
            <span style="font-size: 30px;">
                <?= $escaper->escapeHtml($widgetData['section_label']); ?>
            </span><br />
            <span>
                <?= $escaper->escapeHtml($widgetData['section_desc']); ?>
            </span>
        </div>
        <div class="wk-mp-landing-sellers-container">
            <?php
            $i = 0;
            $count = count($seller_arr);
            foreach ($seller_arr as $seller_id => $products) {
                $i++;
                if ($i <= 4) {
                    $seller_product_count = 0;
                    $profileurl = 0;
                    $shoptitle = '';
                    $logo="noimage.png";

                    $seller_product_count = $sellerCountArr[$seller_id];
                    if (isset($sellerProfileArr[$seller_id][0])) {
                        $profileurl = $sellerProfileArr[$seller_id][0]['profileurl'];
                        $shoptitle = $sellerProfileArr[$seller_id][0]['shoptitle'];
                        $logo = $sellerProfileArr[$seller_id][0]['logo'];
                    }
                    if (!$shoptitle) {
                        $shoptitle = $profileurl;
                    }
                    $logo = $helper->getMediaUrl().'avatar/'.$logo;
                    if (!isset($products[0])) {
                        $products[0] = 0;
                        $products_name_1 = '';
                        $products_url_1 = '';
                        $products_image_url_1 = $placeholderImageUrl;
                    } else {
                        $product_1 = $block->getProduct($products[0]);
                        $products_name_1 = $product_1->getName();
                        $products_url_1 = $product_1->getProductUrl();
                        $products_image_url_1 = $imageHelper->init($product_1, 'product_page_image_small')
                            ->setImageFile($product_1->getFile())->constrainOnly(false)
                            ->keepAspectRatio(true)->keepFrame(true)
                            ->resize(130)->getUrl();
                    }

                    if (!isset($products[1])) {
                        $products[1] = 0;
                        $products_name_2 = '';
                        $products_url_2 = '';
                        $products_image_url_2 = $placeholderImageUrl;
                    } else {
                        $product_2 = $block->getProduct($products[1]);
                        $products_name_2 = $product_2->getName();
                        $products_url_2 = $product_2->getProductUrl();
                        $products_image_url_2 = $imageHelper->init($product_2, 'product_page_image_small')
                            ->setImageFile($product_2->getFile())->constrainOnly(false)
                            ->keepAspectRatio(true)->keepFrame(true)
                            ->resize(130)->getUrl();
                    }

                    if (!isset($products[2])) {
                        $products[2] = 0;
                        $products_name_3 = '';
                        $products_url_3 = '';
                        $products_image_url_3 = $placeholderImageUrl;
                    } else {
                        $product_3 = $block->getProduct($products[2]);
                        $products_name_3 = $product_3->getName();
                        $products_url_3 = $product_3->getProductUrl();
                        $products_image_url_3 = $imageHelper->init($product_3, 'product_page_image_small')
                            ->setImageFile($product_3->getFile())->constrainOnly(false)
                            ->keepAspectRatio(true)->keepFrame(true)
                            ->resize(260)->getUrl();
                    }
                    ?>
                    <div class="wk-mp-landing-sellers-wraper <?php if ($count == $i) { echo "wk_last_seller"; }?>"
                    style="vertical-align:top;">
                        <div class="wk-mp-landing-sellers">
                            <div class="wk-mp-landing-sellers-img1">
                                <a href="<?= $escaper->escapeUrl($products_url_1)?>" 
                                title="<?= $escaper->escapeHtmlAttr($products_name_1);?>">
                                    <img src=<?= $escaper->escapeUrl($products_image_url_1)?> />
                                </a>
                                <a href="<?= $escaper->escapeUrl($products_url_2)?>" 
                                title="<?= $escaper->escapeHtmlAttr($products_name_2);?>">
                                    <img src=<?= $escaper->escapeUrl($products_image_url_2);?> />
                                </a>
                            </div>
                            <div class="wk-mp-landing-sellers-img2">
                                <a href="<?= $escaper->escapeUrl($products_url_3)?>" 
                                title="<?= $escaper->escapeHtmlAttr($products_name_3);?>">
                                    <img src=<?= $escaper->escapeUrl($products_image_url_3);?> />
                                </a>
                            </div>
                            <?php if (!empty($sellerBadgeArr[$seller_id]) && $mpHelper->badgeEnable()) { ?>
                                <div class="wk-mp-landing-sellers-logo" style="border:0;font-weight:600;height:auto;">
                                    <span>Received Badge</span>
                                </div>
                                <div class="wk-mp-landing-sellers-details">
                                    <?php
                                        $j = 0;
                                    foreach ($sellerBadgeArr[$seller_id] as $badge) {
                                        if ($j <= 2) {
                                            ?>
                                        <div style="margin-left:3px;display:inline-block;padding-bottom:5.3%;">
                                            <div class="tooltip">
                                                <img src="<?= $escaper->escapeUrl($badge['badge_url']);?>" 
                                                width="50" height="50">
                                                <span class="tooltiptext" style="width:auto;font-size:11px;">
                                                    <?= $escaper->escapeHtmlAttr($badge['badge_name']); ?>
                                                </span>
                                            </div>
                                        </div>
                                            <?php
                                            $j++;
                                        } else {
                                            ?>
                                            <div style="vertical-align: middle;display: inline-block;font-size: 14px;
                                            font-weight: 600;min-height: 60px;text-transform: capitalize;">
                                                <a href="<?= $escaper->escapeUrl($block->getUrl(
                                                    'mpsellerbadge/badge/index',
                                                    ['shop' => $profileurl]
                                                )); ?>#badge-block" 
                                                title="<?= /* @noEscape */  __("View All Badges") ?>">
                                                    <span><?= $escaper->escapeHtml(__('More...')); ?></span>
                                                </a>
                                            </div>
                                            <?php
                                            break;
                                        }
                                    } ?>
                                </div>
                            <?php } ?>
                            <div class="wk-mp-landing-sellers-logo">
                                <a href="<?= $escaper->escapeUrl($helper
                                ->getRewriteUrl('marketplace/seller/profile/shop/'.$profileurl));?>" 
                                title="<?= /* @noEscape */  __("View Seller's Shop") ?>">
                                    <img src="<?= $escaper->escapeUrl($logo) ?>" style="height:100%; width:100%;">
                                </a>
                            </div>
                            <div class="wk-mp-landing-sellers-details">
                                <div>
                                    <a href="<?= $escaper->escapeUrl($helper
                                    ->getRewriteUrl('marketplace/seller/profile/shop/'.$profileurl));?>" 
                                    title="<?= /* @noEscape */ __("View Seller's Shop") ?>">
                                        <strong><?= $escaper->escapeHtml($shoptitle) ?></strong>
                                    </a>
                                </div>
                                <div>
                                    <?= /* @noEscape */  __('%1 Products', $seller_product_count) ?>
                                </div>
                                <a href="<?= $escaper->escapeUrl($helper
                                ->getRewriteUrl('marketplace/seller/collection/shop/'.$profileurl));?>">
                                    <button class="button" 
                                    title="<?= /* @noEscape */ __("View Seller's Collection") ?>">
                                        <span>
                                            <span>
                                                <?= /* @noEscape */  __('View All'); ?>
                                            </span>
                                        </span>
                                    </button>
                                </a>
                            </div>
                        </div>
                    </div>
                    <?php
                }
            } ?>
        </div>
    </div>
<?php } ?>