<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

?>
<div id="qaauthenticationPopup" data-bind="scope:'qaauthenticationPopup'" style="display: none;">
    <script>
        window.authenticationPopup = <?= /* @noEscape */ \Zend_Json::encode($block->getConfig()); ?>;
    </script>
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
        {
            "#qaauthenticationPopup": {
                "Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout();?>
            },
            "*": {
                "Magento_Ui/js/block-loader": "<?= /* @noEscape */ $block->getViewFileUrl('images/loader-1.gif'); ?>"
            }
        }
    </script>
</div>
