<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Currency switcher
 *
 * @see \Magento\Directory\Block\Currency
 */
$_helper = $this->helper('Smartwave\Porto\Helper\Data');
$cc_list = array(
    'USD'=> ['code'=>'us', 'label'=>'US Dólares - $ USD'],
    'VEF'=> ['code'=>'ve', 'label'=>'Venezuela - Bs. VES'],
);
?>
<?php if ($block->getCurrencyCount() > 1): ?>
<?php $currencies = $block->getCurrencies(); ?>
<?php $currentCurrencyCode = $block->getCurrentCurrencyCode(); ?>
<?php $id = "menu"; ?>
<div class="switcher currency switcher-currency" id="switcher-currency<?php /* @escapeNotVerified */ echo $id?>">
    <strong class="label switcher-label"><span><?php /* @escapeNotVerified */ echo __('Currency') ?></span></strong>
    <div class="actions dropdown options switcher-options">
        <div class="action toggle switcher-trigger" id="switcher-currency-trigger<?php /* @escapeNotVerified */ echo $id?>">
            <strong class="language-<?php echo $block->escapeHtml($block->getCurrentCurrencyCode()) ?>">
                <img src="<?php echo $_helper->getBaseUrl().'wysiwyg/smartwave/porto/flags/'.$cc_list[$currentCurrencyCode]['code'].'.png'; ?>" alt="" />
                <span><?php echo __('Currency') ?></span>
            </strong>
        </div>
        <ul class="dropdown switcher-dropdown" data-mage-init='{"dropdownDialog":{
            "appendTo":"#switcher-currency<?php /* @escapeNotVerified */ echo $id?> > .options",
            "triggerTarget":"#switcher-currency-trigger<?php /* @escapeNotVerified */ echo $id?>",
            "closeOnMouseLeave": false,
            "triggerClass":"active",
            "parentClass":"active",
            "buttons":null}}'>
            <?php foreach ($currencies as $_code => $_name): ?>
                <li class="currency-<?php /* @escapeNotVerified */ echo $_code ?> switcher-option <?php echo $_code==$currentCurrencyCode ? 'active' : '' ?>">
                    <a href="#" data-post='<?php /* @escapeNotVerified */ echo $block->getSwitchCurrencyPostData($_code); ?>'>
                        <img src="<?php echo $_helper->getBaseUrl().'wysiwyg/smartwave/porto/flags/'.$cc_list[$_code]['code'].'.png'; ?>" alt="" />
                        <?php echo $cc_list[$_code]['label'] ?>
                    </a>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
</div>
<?php endif; ?>
