<?php
$partner = $block->getProfileDetail();
$shopUrl = $escaper->escapeHtml($partner['shop_url']);
$sellerbadges = $block->getSellerBadges();
ksort($sellerbadges);
$badgeDesc = [];
?>
<div class="wk_mp_design">
    <?= /* @escapeNotVerified */ $block->getChildHtml("marketplace_seller_top_block"); ?>
    <div class="wk-mp-collection-container">
        <div class="block badge-block-account" id="badge-block">   
            <div class="block-title">
                <strong><span><h4><?= $escaper->escapeHtml(__("Seller Badge(s)")); ?></h4></span></strong>
            </div>
            <fieldset class="fieldset info wk-mp-fieldset">
                <div class="field">
                    <?php if (count($sellerbadges) > 0) {
                        foreach ($sellerbadges as $key => $val) {
                            $badgeDesc[$key]= ['desc' => $val['desc'],'name' => $val['title']];
                            ?>
                            <div class="badge-block-cont">
                                <div class="tooltip">
                                    <img src="<?= $escaper->escapeHtml($val['url']); ?>" width="100" height="100" />
                                </div>
                                <div class="badge-detail">
                                    <div style="margin-left:15px;">
                                        <?php
                                        $sellerDescLenght = strlen($val['desc']);
                                        ?>
                                        <span style="font-weight:900;"><?= $escaper->escapeHtml($val['title'])?></span>
                                        <br />
                                        <span>
                                            <?= $escaper->escapeHtml(substr($val['desc'], 0, 100)); ?>
                                            <?php if ($sellerDescLenght > 100) { ?>
                                                <a href="#!" class="badge" bid="<?= $escaper->escapeHtml($key); ?>">
                                                    <?= $escaper->escapeHtml(__('Read More....')); ?>
                                                </a>
                                            <?php } ?>
                                        </span>
                                    </div>
                                </div>
                            </div>
                        <?php }
                    } else { ?>
                        <div class="wk_profile_alert">
                            <strong><?= $escaper->escapeHtml(__('There is no badge assigned to seller.')); ?></strong>
                        </div> 
                    <?php } ?>
                </div>
            </fieldset>
        </div>
    </div>
</div>
<div id="custom-model-popup">
    <dl>
    </dl>
</div> 
<script type="text/x-magento-init">
    {
        "*": {
            "sellerBadgeDescription": <?= /* @noEscape */ json_encode($badgeDesc); ?>
        }
    }
</script>