<!-- 
/**
 * @category   Webkul
 * @package    Webkul_MpSellerBadge
 * @author     Webkul Software Private Limited
 * @copyright  Copyright (c)  Webkul Software Private Limited (https://webkul.com)
 * @license    https://store.webkul.com/license.html
 */  
-->
<?php
$sellerbadges = $block->getSellerBadges();
ksort($sellerbadges);
$partner = $block->getProfileDetail();
$shopUrl = $escaper->escapeHtml($partner['shop_url']);
$i = 1;
$badgeDesc = [];
?>
<div class="wk-mp-profile-block">
    <div class="block badge-block-account">
        <div class="block-title">   
            <strong><span><h3><?= $escaper->escapeHtml(__("Seller Badge(s)")); ?></h3></span></strong>
        </div>
        <fieldset class="fieldset info wk-mp-fieldset">
            <div class="field">
                <?php if (count($sellerbadges) > 0) {
                    foreach ($sellerbadges as $key => $val):
                        $badgeDesc[$key] = ['desc' => $val['desc'],'name' => $val['title']];
                        ?>
                        <div class="badge-block-cont">
                            <div class="tooltip">
                                <img src="<?= $escaper->escapeHtml($val['url']) ;?>" width="100" height="100" title= "">
                            </div>
                            <div class="badge-detail">
                                <div style="margin-left:15px;">
                                    <?php
                                    $sellerDescLenght = strlen($val['desc']);
                                    echo '<span style="font-weight:900;">'.$escaper->escapeHtml($val['title']);
                                    echo '</span>';
                                    echo "<br />";
                                    echo "<span>";
                                    echo $escaper->escapeHtml(substr($val['desc'], 0, 100));
                                    if ($sellerDescLenght > 100) { ?>
                                        <a href="#!" class="badge" bid="<?= $escaper->escapeHtml($key); ?>">
                                            <?= $escaper->escapeHtml(__('Read More....')); ?>
                                        </a>
                                    <?php } ?>
                                    </span>
                                </div>
                            </div>
                        </div>
                    <?php endforeach; ?>
                <?php } else { ?>
                    <div class="wk_profile_alert">
                        <strong><?= $escaper->escapeHtml(__('There is no badge assigned to seller.')); ?></strong>
                    </div>          
                <?php } ?>
            </div>
        </fieldset>
    </div>
    <?php if (count($sellerbadges) > 1): ?>
        <div class="wk-mp-collection-view-btn">
            <a href="<?= $escaper->escapeUrl($block->getUrl(
                'mpsellerbadge/badge/index',
                ['shop' => $shopUrl]
            )); ?>" title="<?= $escaper->escapeHtml(__('All Badges')); ?>">
                <?= $escaper->escapeHtml(__('View All Badges')); ?>
            </a>
        </div>
    <?php endif; ?>
</div>

<div id="custom-model-popup">
    <dl>
    </dl>
</div> 

<script type="text/x-magento-init">
    {
        "*": {
            "sellerBadgeDescription": <?= /* @noEscape */ json_encode($badgeDesc); ?>
        }
    }
</script>