<?php
/** @var \Mirasvit\CatalogLabel\Block\Product\Label $block */
/** @var \Mirasvit\CatalogLabel\Model\Label\Display $display */

$displays = $block->getDisplays();
$block->setLabelObjectsArray($displays);
$isProductList = $block->isProductList();
?>
<?php if($block->getFullActionCode() != 'checkout_cart_index'): ?>
    <?php foreach ($displays as $display): ?>
      <?php
      // print_r('<pre>');
      // print_r($display->getData());
      // print_r('</pre>');
      ?>
        <?php if ($display->getViewImage() ): ?>
            <?php //echo "A"; ?>
            <?php if ($display->getUrl() || $display->getDescription()): ?>
                <?php // echo "B"; ?>
                <span style="<?= $display->getUrl() ? 'cursor: pointer;' : '' ?>"
                onclick="window.location = '<?php echo $display->getUrl() ? $display->getUrl() : '#' ?>'"
                    title="<?php echo $display->getDescription() ?>"
                <?= ($display->getUrl() && $isProductList)
                    ? "onmouseover = 'mLabelLinkEnterFunction(this, this.parentNode)'
                    onmouseout  = 'mLabelLinkOutFunction(this, this.parentNode)'" : ''?>>
                <?php if ($display->getUrl() && $isProductList): ?>
                   <script>
                        function mLabelLinkEnterFunction(x, xparent) {
                            var url = '<?php echo $display->getUrl();?>';
                            if (typeof url != 'undefined') {
                                currentmLabelEnterCustomUrl = xparent.href;
                                xparent.href = url;
                            }
                        }

                        function mLabelLinkOutFunction(x, xparent) {
                            if (currentmLabelEnterCustomUrl) {
                                xparent.href = currentmLabelEnterCustomUrl;
                            }
                        }
                    </script>
                <?php endif; ?>
            <?php endif; ?>
                <?php // echo "C"; ?>
                <?php
                //var_dump($block->getPlaceholderCode());
                //var_dump($display->getType());
                //var_dump($display->getPosition());
                //var_dump($display->getViewImage());
                ?>
                <div class="cataloglabel cataloglabel-product-top-label cataloglabel-<?php
                        echo $block->getPlaceholderCode();
                    ?> cataloglabel-<?php
                        echo $display->getType();
                    ?> position-<?php
                        echo $display->getPosition();
                    ?>" style="<?php echo $display->getViewStyle(); ?>background:url('/pub/media/cataloglabel<?php echo $display->getViewImage() ?>'); background-repeat: no-repeat;">
                    <?php echo $display->getTitle() ?>
                </div>
                <?php $block->setLabelPositionCount($display); ?>
            <?php if ($display->getUrl() || $display->getDescription()): ?>
                </span>
            <?php endif; ?>
        <?php else: ?>
            <?php // echo "D"; ?>
            <div class="cataloglabel cataloglabel-product-top-label cataloglabel-<?php echo $block->getPlaceholderCode();?>
                cataloglabel-<?php echo $display->getType();?>
                position-<?php echo $display->getPosition();?>"
                style="<?php echo $display->getViewStyle(); ?>" >
                <?php echo $display->getTitle()?>
            </div>
        <?php  endif ?>
    <?php endforeach ?>
<?php endif ?>
