<div class="row">
    <div class="col-sm-6 col-lg-3">
        <div class="block">
            <div class="block-title"><strong><span>Deja que te ayudemos</span></strong></div>
            <div class="block-content">
                <ul class="links">
                    <li><a href="{{store url=""}}">Tu Cuenta</a></li>
                    <li><a href="{{store url=""}}">Tus Órdenes</a></li>
                    <li><a href="{{store url=""}}">Guía de Tallas</a></li>
                    <li><a href="{{store url=""}}">Preguntas Frecuentes</a></li>
                    <li><a href="{{store url=""}}">Centro de Resoluciones</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="col-sm-6 col-lg-3">
        <div class="block">
            <div class="block-title"><strong><span>Información de Compras</span></strong></div>
            <div class="block-content">
                <ul class="links">
                    <li><a href="{{store url=""}}">Opciones de Pago Seguro</a></li>
                    <li><a href="{{store url=""}}">Compra con Puntos</a></li>
                    <li><a href="{{store url=""}}">Recarga Tu Balance</a></li>
                    <li><a href="{{store url=""}}">Envíos & Entrega</a></li>
                    <li><a href="{{store url=""}}">Devoluciones & Reembolsos</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="col-sm-6 col-lg-3">
        <div class="block">
            <div class="block-title"><strong><span>Haz Dinero con Nosotros</span></strong></div>
            <div class="block-content">
                <ul class="links">
                    <li><a href="{{store url=""}}">Vende en Ferreteo</a></li>
                    <li><a href="{{store url=""}}">Publicíta Tus Productos</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="col-sm-6 col-lg-3">
        <div class="block">
            <div class="block-title"><strong><span>Conócenos</span></strong></div>
            <div class="block-content">
                <ul class="links">
                    <li><a href="{{store url=""}}">Carreras</a></li>
                    <li><a href="{{store url=""}}">Acerca de Nosotros</a></li>
                    <li><a href="{{store url=""}}">Contáctanos</a></li>
                    <li><a href="{{store url=""}}">Blog</a></li>
                    <li><a href="{{store url=""}}">News</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>