<ul class="footer-bottom-links">
    <li><a href="">Términos de Uso</a></li>
    <li><a href="">Privacidad</a></li>
    <li><a href="">Cookies</a></li>
</ul>
<div class="payment-logos">
    <img src="{{media url=&quot;wysiwyg/smartwave/porto/homepage/payment_icons.png&quot;}}" alt="" />
</div>
<div class="footer-currency-switcher">
    {{block class="Magento\Directory\Block\Currency" name="currency" template="currency.phtml" id_modifier="footer"}}
</div>