<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
?>
<div class="toolbar-filter tfilter" style="display: none">
   <label class="tfilter-label" for="filter"><?= $block->escapeHtml(__('Refine By')) ?></label>
  <div class="marcaofabricante">
    <div class="marcaofabricante-title">

    </div>
    <div class="marcaofabricante-content" style="display: none;">
    </div>
  </div>
  <div class="price">
    <div class="price-title">

    </div>
    <div class="price-content" style="display: none;">
      <ol class="items">
          <li class="item">
              <div id="ln_tfilter_container_price" class="ln_tfilter_container">
                  <div id="ln_tfilter_range_price">
                          <div class="ln_tfilter_from">
                              <label for="ln_tfilter_from_price">$</label>
                              <input id="ln_tfilter_from_price" placeholder="min" class="ln_tfilter_input_from ln_tfilter_range_input ln_tfilter_range_input_from" type="text" >
                          </div>
                          <div class="ln_tfilter_to">
                              <label for="ln_tfilter_to_price">$</label>
                              <input id="ln_tfilter_to_price" placeholder="max" class="ln_tfilter_input_to ln_tfilter_range_input ln_tfilter_range_input_to" type="text" >
                          </div>
                          <div class="ln_tfilter_go">
                              <button class="submit-tfilter-price"><?= $block->escapeHtml(__('Go')) ?></button>
                          </div>
                          <div style="clear: both"></div>
                      </div>
                  </div>
          </li>
      </ol>
    </div>
  </div>
</div>
<div class="toolbar-sorter sorter">
    <label class="sorter-label" for="sorter"><?= $block->escapeHtml(__('Sort By')) ?></label>
    <!-- <div class="sorter-wrap"> -->
    <select id="sorter" data-role="sorter" class="sorter-options modify-select">
        <?php foreach ($block->getAvailableOrders() as $_key => $_order) :?>
            <option value="<?= $block->escapeHtmlAttr($_key) ?>"
                <?php if ($block->isOrderCurrent($_key)) :?>
                    selected="selected"
                <?php endif; ?>
                >
                <?= $block->escapeHtml(__($_order)) ?>
            </option>
        <?php endforeach; ?>
    </select>
    <!-- </div> -->
    <?php if ($block->getCurrentDirection() == 'desc') :?>
        <a title="<?= $block->escapeHtmlAttr(__('Set Ascending Direction')) ?>"
           href="#"
           class="action sorter-action sort-desc"
           data-role="direction-switcher"
           data-value="asc">
            <span><?= $block->escapeHtml(__('Set Ascending Direction')) ?></span>
        </a>
    <?php else :?>
        <a title="<?= $block->escapeHtmlAttr(__('Set Descending Direction')) ?>"
           href="#"
           class="action sorter-action sort-asc"
           data-role="direction-switcher"
           data-value="desc">
            <span><?= $block->escapeHtml(__('Set Descending Direction')) ?></span>
        </a>
    <?php endif; ?>
</div>
<script type="text/javascript">
    require([
        'jquery',
        'domReady!'
    ], function ($) {
        $('.toolbar-filter .marcaofabricante .marcaofabricante-title').empty();
        $('.toolbar-filter .marcaofabricante .marcaofabricante-content').empty();
        $('.toolbar-filter .marcaofabricante .price-title').empty();
        $('<input type="text" class="layer-search-box-marcaofabricante" code="manufacturer">').appendTo($('.toolbar-filter .marcaofabricante .marcaofabricante-content').first());
        $('.toolbar-filter .marcaofabricante .marcaofabricante-title').first().text($('.filter-options-title.marcaofabricante').text());
        $('.filter-options-content.marcaofabricante .ln-items-manufacturer').first().clone().appendTo($('.toolbar-filter .marcaofabricante .marcaofabricante-content').first());
        $('.toolbar-filter .price .price-title').first().text($('.filter-options-title.precio').text());
        $('.bottom-toolbar .toolbar-filter').remove();
        $('.toolbar-filter').show();
    });
</script>