<?php
if ($block->getQuestion()->getSize() != 0) {
    foreach ($block->getQuestion() as $ky) {
        $qid=$ky->getQuestionId();
    }
}
$customer_id=$block->getCustomer()->getId();
$getinfo = $block->getQuestion();
$proinfo = $block->getProduct();

?>
<div class="wk-mp-design block" id="wk-bodymain">
    <div class="block-title">
    <span><?= /* @noEscape */ __('Buyer Question') ?></span>
    </div>
    <div class="question">
            <strong><span><h4><?= /* @noEscape */ __('Question') ?></h4></span></strong>

        <div class ="fieldset wk_mp_fieldset">
             <div>
                  <div class='pimg'>
                      <a href='<?= /* @noEscape */ $proinfo->getProductUrl(); ?>'
                      target="_blank" class='hrefa' >
                      <img src="<?= /* @noEscape */
                        $block->imageHelperObj()->init($proinfo, 'customer_account_product_review_page')->getUrl();?>" 
                      class="wk_mpqa_image" /> </a>
                   </div>
                 <div class='pinfo'>
                        <?php $procontent =
                        strlen($proinfo->getDescription())>27?
                        substr($proinfo->getDescription(), 0, 27)."..":
                        $proinfo->getDescription(); ?>
                     <div>
                         <label class="plabl"><?= /* @noEscape */ __('Product Name:') ?></label>
                         <a href='<?= /* @noEscape */ $proinfo->getProductUrl(); ?>' target="_blank" class='hrefa' >
                             <label class="nlabl"> <?= /* @noEscape */ $proinfo->getName(); ?> </label>
                         </a>
                     </div>
                     <div>
                         <label class="plabl"><?= /* @noEscape */ __('Product Description:') ?></label>
                         <span class="wk_desc"><?= /* @noEscape */ $proinfo->getDescription(); ?> </span>
                     </div>
                 </div>
             </div>
             <div class='clr'></div>
                   <div class='mainquest1' >
                       <div class='respond' id='<?= /* @noEscape */ $getinfo->getQuestionId(); ?>'>
                           <div>

                                   <label id='mlabl'><?= /* @noEscape */ $getinfo->getQaNickname().' ('.__('Buyer').') :'?> </label>

                               <strong><?= /* @noEscape */ $getinfo->getSubject();?></strong>
                                    <span class="wk-date"><?= /* @noEscape */
                                    $block->formatDate($getinfo->getCreatedAt(), IntlDateFormatter::MEDIUM, true);?>
                                    </span>
                           </div>
                           <div class='conten main-question-container'>
                               <span class="wk_prewrap"><?= /* @noEscape */ $getinfo->getContent(); ?>
                               </span>
                            </div>
                                <div class="textarea-header">
                                    <strong><span><?= /* @noEscape */ __('Post your answer') ?></span></strong>
                                    <button class="button wk-mp-btn btn"
                                    title="<?= /* @noEscape */ __('Submit') ?>"
                                    type="button" data-id="<?= /* @noEscape */
                                    $getinfo->getQuestionId(); ?>">
                                        <span><span><?= /* @noEscape */ __('Submit') ?></span></span>
                                    </button>
                                </div>
                     <div>
                          <div class='txtcomment1'>
                            <div class='margres'>
                                <textarea id='maincont' class="txtsize mpqatext" style="width:100%"></textarea>
                            </div>
                          </div>
                     </div>
                </div>
                 <!-- old answers -->
                    <?php
                    $answers=$block->getAnswers();
                    foreach ($answers as $key) {

                        ?>
                 <div class='respond newres'>

                       <div class="wk-mp-user">
                          <?php if ($key->getRespondType()=='Customer') {
                                $cname=$block->getCustomerById($key->getRespondFrom())->getName();
                                ?>
                           <label class='rlabl' style="font-weight: bold;">
                                <?= /* @noEscape */ __('Customer').'('.$cname.')'; ?></label>
                                <?php
                          } else {    ?>
                           <label class='rlabl'
                           style="font-weight: bold;">
                                <?= /* @noEscape */ $key->getRespondType(); ?></label>
                            <?php } ?>
                       </div>
                       <div class='conten '>
                           <span class="wk_prewrap"><?= /* @noEscape */ $key->getContent(); ?>
                        </span>
                       </div>
                    <div class='dte'>

                                  <?= /* @noEscape */
                                    $block->formatDate($key->getCreatedAt(), IntlDateFormatter::MEDIUM, true);?>
                       </div>
                   </div>
                        <?php
                    }
                    ?>
                 <!-- old -->
            </div>
                <div class="back-button">
                        <button onclick="history.back();"
                        class="button mpqa-back" title="<?= /* @noEscape */ __('Back') ?>" type="button">
                                <span><span><?= /* @noEscape */ __('Back') ?></span></span>
                        </button>
                </div>
        </div>
    </div>
</div>

<?php
$formData = [
    'submitanswer_url'=> $block->getUrl("mpqa/mpqaquest/saveanswer", ["_secure" => $block->getIsSecure()]),
    'question_id' => $getinfo->getQuestionId(),
    'customer_id'   => $customer_id
];
$serializedFormData = $block->getJsonHelper()->jsonEncode($formData);
?>
<script type="text/x-magento-init">
    {
        "*": {
            "giveanswer": <?= /* @noEscape */ $serializedFormData; ?>
        }
    }
</script>
