<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_Mpqa
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
$createBlock = $block->getLayout()->createBlock(\Webkul\Mpqa\Block\Viewall::class);
$_helper = $createBlock->getMpHelper();
$isPartner= $_helper->isSeller();
$magentoCurrentUrl = $block->getCurrentUrl();
$isSellerGroup = $_helper->isSellerGroupModuleInstalled();
?>
<?php
if ($isPartner) {
    if (($isSellerGroup && $_helper->isAllowedAction('mpqa/mpqaquest/showquestions')) || !$isSellerGroup) { ?>
        <li class="nav item <?= /* @noEscape */
        strpos($magentoCurrentUrl, 'mpqa/mpqaquest/showquestions')? "current":"";?>">
            <?php if (strpos($magentoCurrentUrl, 'mpqa/mpqaquest/')!== false) { ?>
                <strong><?= /* @noEscape */ __('Manage MPQA') ?></strong>
                <?php
            } else { ?>
                <a href="<?= /* @noEscape */
                $block->getUrl('mpqa/mpqaquest/showquestions', ['_secure' => $createBlock->getIsSecure()]); ?>">
                    <?= /* @noEscape */ __('Manage MPQA') ?>
                </a>
                <?php
            } ?>
        </li>
<?php }
} ?>
