<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_Mpqa
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
$helper = $block->getMpqaHelper();
$product = $block->getCurrentProduct();//get current product
$product_id=$block->getCurrentProduct()->getId();
$seller_id=$block->getSellerId();
$login=0;

if ($helper->checkLogin()) {
    $buyer_id = $helper->getCustomerId();
    $readonly = "readonly='readonly'";
    $login=1;
} else {
    $buyer_email = '';
    $buyer_name = '';
    $readonly = '';
    $buyer_id='';
}
$collection = $block->getQuestions();
?>
<div class="box-collateral box-description">
<div>
    <div class='pimg'>
        <a href='<?= /* @noEscape */ $product->getProductUrl(); ?>' target="_blank" class='hrefa' >
        <img src="<?= /* @noEscape */
             $block->imageHelperObj()->init($product, 'product_page_image_medium')->getUrl();?>"
             class="wk_mpqa_image" /> </a>
    </div>
    <div class='pinfo'>
        <?php $procontent =
        strlen($product->getDescription())>27?
        substr($product->getDescription(), 0, 27)."..":$product->getDescription(); ?>
        <div>
            <label class="plabl"><?= /* @noEscape */ __('Product Name:') ?></label>
            <a href='<?= /* @noEscape */ $product->getProductUrl(); ?>' target="_blank" class='hrefa' >
                <label class="nlabl"> <?= /* @noEscape */ $product->getName(); ?> </label>
            </a>
        </div>
        <div>
            <label class="plabl"><?= /* @noEscape */ __('Product Description:') ?></label>
            <span class="nlabl"><?= /* @noEscape */ $product->getDescription(); ?> </span>
        </div>
    </div>
</div>

        <div id="search-bar">
            <form action="<?= /* @noEscape */
            $block->getUrl('mpqa/customer/viewall/').'id/'.$product_id;?>"
            method="post" class="search-form">
                <div class="search_bar">
                    <input type="text" placeholder="<?= /* @noEscape */ __('Search or Ask Question')?>"
                    name="q" id="wk-searchqa" value="<?= /* @noEscape */
                    $block->escapeHtml($block->getParamsRequest()->getParam('q')) ?>">
                </div>
                <div class="search_action"><button class="search_button action primary">
                    <span><?= /* @noEscape */ __('Search')?></span></button></div>
            </form>
            <span class="wk-header-count">
                <?= /* @noEscape */ $block->getQuestionsCount() ?>
            </span><span class="wk-header-text">
                <?= /* @noEscape */ __('Questions')?>
            </span>
            <span class="wk-header-count">
                <?= /* @noEscape */ $block->getAnswersCount() ?></span>
                <span class="wk-header-text"><?= /* @noEscape */ __('Answers')?></span>
        </div>
        <div class="question-header">
            <h4 id="header-text"><?= /* @noEscape */ __('Displaying Questions')?></h4>
            <?php
            if ($block->getParamsRequest()->getParam('q')!='') { ?>
                    <span class="wk-qa-action-viewall" id="wk-qa-action-helpful">
                        <span class="wk-qa-action-label">
                            <?= /* @noEscape */ $block->escapeHtml($block->getParamsRequest()->getParam('q')); ?></span>
                        <a href="<?= /* @noEscape */
                        $block->getUrl('mpqa/customer/viewall', ['id'=>$block->getParamsRequest()->getParam('id')]) ?>">
                            <button class="wk-qa-action-button-viewall">
                                <span class="wk-qa-action-button-close"><?= /* @noEscape */ __('Close')?></span>
                            </button>
                        </a>
                    </span>
                <?php }
            if (array_key_exists("helpful", $block->getParamsRequest()->getParams())) { ?>
                    <span class="wk-qa-action-viewall" id="wk-qa-action-helpful">
                        <span class="wk-qa-action-label"><?= /* @noEscape */ __('Most Helpful') ?></span>
                        <a href="<?= /* @noEscape */
                        $block->getUrl('mpqa/customer/viewall', ['id'=>$block->getParamsRequest()->getParam('id')]) ?>">
                            <button class="wk-qa-action-button-viewall">
                                <span class="wk-qa-action-button-close">Close</span>
                            </button>
                        </a>
                    </span>
                <?php }
            if (array_key_exists("recent", $block->getParamsRequest()->getParams())) { ?>
                    <span class="wk-qa-action-viewall" id="wk-qa-action-recent">
                        <span class="wk-qa-action-label"><?= /* @noEscape */ __('Most Recent') ?></span>
                        <a href="<?= /* @noEscape */
                        $block->getUrl('mpqa/customer/viewall', ['id'=>$block->getParamsRequest()->getParam('id')]) ?>">
                            <button class="wk-qa-action-button">
                                <span class="wk-qa-action-button-close"><?= /* @noEscape */ __('Close')?></span>
                            </button>
                        </a>
                    </span>
                <?php }
            ?>
            <a href="<?=/* @noEscape */
            $block->getUrl('mpqa/customer/viewall/').'id/'.$product_id;?>/recent"
            class="header-links">
            <button class="action primary"><?= /* @noEscape */ __('Most Recent')?>
            </button></a>
            <a href="<?= /* @noEscape */
            $block->getUrl('mpqa/customer/viewall/').'id/'.$product_id;?>/helpful"
            class="header-links"><button class="action primary">
                <?= /* @noEscape */ __('Most Helpful')?></button></a>
        </div>

     <div class="all-questions">
        <?php
        foreach ($collection as $key) {     ?>
            <div  id="q-<?= /* @noEscape */ $key->getQuestionId();?>">
            <div class="question">
                <div class="qlogo"><span>Q</span></div>
                <div class="ques">
                    <div class="subj">
                        <strong><span> <?= /* @noEscape */ $key->getSubject(); ?></span></strong>
                    </div>
                    <div class="cont"><span class="wk_prewrap"><?= /* @noEscape */ $key->getContent(); ?> </span></div>
                    <div class="ques-user-info">
                        <span><?= /* @noEscape */ __('by ')?></span>
                        <span class="wk_bold">
                            <?= /* @noEscape */ $key->getQaNickname()?>
                        </span><span><?= /* @noEscape */ __(' on ')?></span>
                        <span><?= /* @noEscape */
                        $block->formatDate($key->getCreatedAt(), \IntlDateFormatter::MEDIUM) ?>
                        </span><br/>
                    </div>
                </div>
            </div>
            <?php
            $answers=$block->getQuestionAnswers($key->getQuestionId());
            $answer_count = $block->getAnswerCount($key->getQuestionId());
            if ($answer_count==0) { ?>
                <div class="answer">
                    <div class="alogo" id="q-<?= /* @noEscape */ $key->getQuestionId();?>"><span>A</span></div>
                    <div class="answ"><a class="qa-ans">
                        <button class="action primary">
                            <span><?= /* @noEscape */ __('Give Answer')?></span>
                        </button></a></div>
                </div>
                <?php
            } else {?>
                <div class="answer">
                        <div class="alogo" id="q-<?= /* @noEscape */ $key->getQuestionId();?>">
                        <span>A</span></div>
                <?php $i=0;
                foreach ($answers as $ans) {
                    $likes=0;
                    $dislikes=0;
                    $reviews=$block->getReview($ans->getAnswerId());
                    $if_iscustomer=2;

                    foreach ($reviews as $key) {

                        if ($key->getLikeDislike()==1) {
                            $likes++;
                        } else { $dislikes++;
                        }
                        if ($key->getReviewFrom()==$buyer_id) {
                            $if_iscustomer=$key->getLikeDislike();
                        }
                    }

                    ?>
                        <div class="answ"><span class="wk_prewrap"><?= /* @noEscape */ $ans->getContent() ?></span>
                            <div class="user-info">
                                <span><?= /* @noEscape */ __('by ')?></span>
                                <span class="wk_bold <?php if ($ans->getRespondType()=='Admin') {
                                    echo 'wk_admin';
                                                     } elseif ($ans->getRespondType()=='Seller') {
                                                         echo 'wk_seller';} ?>">
                                <?= /* @noEscape */ $ans->getRespondNickname()?>
                            </span>
                            <span>
                                <?= /* @noEscape */ __(' on ')?>
                            </span>
                            <span>
                                <?= /* @noEscape */
                                $block->formatDate($ans->getCreatedAt(), \IntlDateFormatter::MEDIUM)?>
                            </span><br/>
                                <div class="reviews">

                                    <span class="<?php if ($if_iscustomer==1) { echo 'liked';
                                                 } else { echo 'like';
                                                 }?>" title="like"
                                                 dataid='<?= /* @noEscape */ $ans->getAnswerId();?>' >
                                                </span>
                                    <span><?= /* @noEscape */ $likes; ?></span>

                                    <span class="<?php if ($if_iscustomer==0) { echo 'disliked';
                                                 } else { echo 'dislike';
                                                 } ?>" title="dislike"
                                                 dataid='<?= /* @noEscape */ $ans->getAnswerId();?>'>
                                                </span>
                                    <span><?= /* @noEscape */ $dislikes; ?></span>
                                </div>
                            </div>
                        </div>

                    <?php  //
                }
                if ($answer_count>1) {?>
                    <div class="answ more">
                        <a class="qa-ansmore" dataid='<?= /* @noEscape */ $ans->getQuestionId();?>' >
                        <span>
                            <?= /* @noEscape */ __('View More').'('.($answer_count -1).')'?>
                        </span></a></div>
                </div><?php
                } else {    ?>
                    <div class="answe">
                        <a class="qa-ans"><button class="action primary">
                            <span>
                                <?= /* @noEscape */ __('Give Answer') ?>
                                </span></button></a></div></div>    <?php
                }
            }
            ?>
            </div>
            <?php
        }

        ?>
        <div class="mainprt">
        <a class="qa-question">
            <button class="action primary">
                <span><?= /* @noEscape */ __('Ask Question');?>
                </span>
            </button>
        </a>
        </div>

    </div>
    <?= /* @noEscape */ $block->getPagerHtml();?>
</div>

<!-- answer pop up -->
<div class="ask-que">
    <div id="wk-qa-ask-data" style="display:none">
        <form id="qa-ans-form" method="post" action="#" class="fieldset">
            <div class="form-list field required">
                <label class="label"><?= /* @noEscape */ __('Your Answer') ?> :</label>
                <textarea  name="qa_answer"
                class="queryquestion wk-contact_input_fields required-entry" 
                style="width:100%;"></textarea>
                <label class="label"><?= /* @noEscape */ __('Name to Display') ?> :</label>
                <input type="text" name="qa_nickname" class="wk-contact_input_fields required-entry"/>
                <input type="hidden" name="customer_id" value="<?= /* @noEscape */ $buyer_id; ?>" >
                <input type="hidden" name="seller_id" value="<?= /* @noEscape */ $seller_id; ?>"/>
                <input type="hidden" name="product_id" value="<?= /* @noEscape */ $product_id;?>" />
                <input type="hidden" name="question_id" value="" id="question-id">
            </div>
        </form>
    </div>
</div>
<!-- question pop up -->
<div class="ask-que">
    <div id="wk-qa-ask-qa" style="display:none">
        <form id="qa-ques-form" method="post" action="#" class="fieldset">
            <div class="form-list field required">
                <label class="label"><?= /* @noEscape */ __('Subject') ?> :</label>
                <input type="text" name="qa_subject" id="sub" class="wk-contact_input_fields required-entry"/>
                <label class="label"><?= /* @noEscape */ __('Query') ?> :</label>
                <textarea  name="qa_content"
                id="content" class="queryquestion wk-contact_input_fields required-entry"
                style="width:100%;"></textarea>
                <label class="label"><?= /* @noEscape */ __('Name to Display') ?> :</label>
                <input type="text" name="qa_nickname" id="qa_nickname" class="wk-contact_input_fields required-entry"/>
                <input type="hidden" name="customer_id" value="<?= /* @noEscape */ $buyer_id; ?>" >
                <input type="hidden" name="seller_id" value="<?= /* @noEscape */ $seller_id; ?>"/>
                <input type="hidden" name="product_id" value="<?= /* @noEscape */ $product_id;?>" />
            </div>
        </form>
    </div>
</div>


<?php
$url = $block->getUrl('*/*/*', ['_current' => true, '_use_rewrite' => true]);
$login_url = $block->getUrl(
    'customer/account/login',
    ['referer' => base64_encode($url)]
);
$formData = [
    'viewall_ans_url' =>$block->getUrl("mpqa/customer/viewallanswer", ["_secure" => $block->getIsSecure()]),
    'reviewanswer_url' => $block->getUrl("mpqa/customer/reviewanswer", ["_secure" => $block->getIsSecure()]),
    'submitanswer_url'=> $block->getUrl("mpqa/customer/submitanswer", ["_secure" => $block->getIsSecure()]),
    'question_url'  => $block->getUrl('mpqa/customer/savequestion', ["_secure" => $block->getIsSecure()]),
    'product_id' => $product_id,
    'buyer_id'  =>  $buyer_id,
    'islogin'     => $login,
    'seller_id'   => $seller_id,
    'login_url' => $login_url
];
$serializedFormData = $block->getJsonHelper()->jsonEncode($formData);
?>
<script type="text/x-magento-init">
    {
        "*": {
            "mpqa_tab": <?= /* @noEscape */ $serializedFormData; ?>
        }
    }
</script>
